# .github/workflows/imagepush.yml
name: Docker Image Build and Push

on:
  workflow_call:

jobs:
  image_push:
    runs-on: self-hosted
    env:
      DOCKER_IMAGE: joelirish/petclinic-app:${{ github.sha }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Ensure Docker is running
        run: |
          sudo systemctl start docker
          sudo docker info

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | sudo docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          sudo docker build -t $DOCKER_IMAGE .

      - name: Push Docker Image
        run: |
          sudo docker push $DOCKER_IMAGE
