# .github/workflows/sonar.yml

name: SonarCloud Scan

on:
  workflow_call:

jobs:
  sonar:
    name: Run SonarCloud Scan
    runs-on: self-hosted # Replace with the actual label if different

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run SonarCloud Scan
        run: mvn sonar:sonar \
          -sonar.projectKey=joel84irish_DevSecops_Pipeline \
          -sonar.organization=joel84irish \
          -sonar.host.url=https://sonarcloud.io\
          -sonar.login=${{ secrets.SONAR_TOKEN }}


          


